services:
  mysql:
    image: mysql:8.0
    container_name: diprochil-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: diprochil
      MYSQL_USER: diprochil_user
      MYSQL_PASSWORD: diprochil_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
